apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-0
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName:
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/mysql-0
    server: node5.cluster.local
